# Generated by Django 4.1.1 on 2022-10-01 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_transactiontracker_org_sponsor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactiontracker",
            name="org_sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_org_sponsor",
                to="base.orgapplication",
            ),
        ),
        migrations.AlterField(
            model_name="transactiontracker",
            name="physical_sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_physical_sponsor",
                to="base.physicalapplication",
            ),
        ),
    ]
