# Generated by Django 4.1.1 on 2022-10-02 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_orgapplication_date_physicalapplication_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orgapplication",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="physicalapplication",
            old_name="date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="transactiontracker",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
