# Generated by Django 4.1.1 on 2022-10-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_student_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
