# Generated by Django 4.1.1 on 2022-10-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_student_unpaid_tution_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
